# -*- coding: utf-8 -*-
"""orion_wake_word.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SwRxKHI9WbHLmvgMDO4aMENEBKGaSCXw
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content

# 1. Prepare Python 3.11 virtual environment
!pip install -q uv
!uv python install 3.11
!uv venv --clear --python 3.11 /content/.venv

# 2. Clone repositories to specific working commits
!git clone -q https://github.com/dscripka/openWakeWord /content/openWakeWord
!git -C /content/openWakeWord checkout -q 368c03716d1e92591906a84949bc477f3a834455

!git clone -q https://github.com/rhasspy/piper-sample-generator /content/piper-sample-generator
!git -C /content/piper-sample-generator checkout -q 2971426a55072f7d22fec416ca7800df8bd23207

# 3. Install dependencies with pinned SciPy, NumPy, and Matplotlib backend
!uv pip install --python /content/.venv \
  "numpy==1.26.4" "scipy==1.13.1" matplotlib-inline \
  datasets tqdm mutagen==1.47.0 tensorflow torchinfo==1.8.0 \
  torchmetrics==1.2.0 speechbrain==0.5.14 audiomentations==0.33.0 \
  torch-audiomentations==0.11.0 acoustics==0.2.6 onnx onnx2tf \
  onnx_graphsurgeon sng4onnx "ai-edge-litert>=2.0.2" "setuptools<70.0.0" \
  pronouncing==0.2.0 deep-phonemizer==0.0.19 onnxscript webrtcvad \
  onnxruntime pyyaml piper-tts librosa soundfile

# 4. Link repos in editable mode
!uv pip install --python /content/.venv --no-deps -e /content/openWakeWord
!uv pip install --python /content/.venv --no-deps -e /content/piper-sample-generator

# 1. Base OpenWakeWord feature models
!mkdir -p /content/openWakeWord/openwakeword/resources/models
!wget -nc -q https://github.com/dscripka/openWakeWord/releases/download/v0.5.1/embedding_model.onnx -P /content/openWakeWord/openwakeword/resources/models/
!wget -nc -q https://github.com/dscripka/openWakeWord/releases/download/v0.5.1/embedding_model.tflite -P /content/openWakeWord/openwakeword/resources/models/
!wget -nc -q https://github.com/dscripka/openWakeWord/releases/download/v0.5.1/melspectrogram.onnx -P /content/openWakeWord/openwakeword/resources/models/
!wget -nc -q https://github.com/dscripka/openWakeWord/releases/download/v0.5.1/melspectrogram.tflite -P /content/openWakeWord/openwakeword/resources/models/

# 2. Piper TTS LibriTTS voice model
!mkdir -p /content/piper-sample-generator/models
!wget -nc -q https://github.com/rhasspy/piper-sample-generator/releases/download/v2.0.0/en_US-libritts_r-medium.pt -O /content/piper-sample-generator/models/en_US-libritts_r-medium.pt

# 3. Negative features (ACAV100M 2,000 hrs & Validation features)
!wget -nc -q --show-progress https://huggingface.co/datasets/davidscripka/openwakeword_features/resolve/main/openwakeword_features_ACAV100M_2000_hrs_16bit.npy -O /content/openwakeword_features_ACAV100M_2000_hrs_16bit.npy
!wget -nc -q --show-progress https://huggingface.co/datasets/davidscripka/openwakeword_features/resolve/main/validation_set_features.npy -O /content/validation_set_features.npy

from pathlib import Path
import os

# 1. Complete Piper sample generator adapter
adapter_code = '''import os
from pathlib import Path
import librosa
import soundfile as sf
import torch

# Bypass PyTorch weights_only constraint
_orig_load = torch.load
def _safe_load(*args, **kwargs):
    kwargs["weights_only"] = False
    return _orig_load(*args, **kwargs)
torch.load = _safe_load

from piper_sample_generator.__main__ import generate_samples as _generate

MODEL = "/content/piper-sample-generator/models/en_US-libritts_r-medium.pt"

def generate_samples(
    text,
    max_samples,
    output_dir,
    batch_size=1,
    noise_scales=None,
    noise_scale_ws=None,
    length_scales=None,
    file_names=None,
    **_,
):
    _generate(
        text=text,
        model=MODEL,
        max_samples=max_samples,
        output_dir=output_dir,
        batch_size=batch_size,
        noise_scales=noise_scales or (0.667,),
        noise_scale_ws=noise_scale_ws or (0.8,),
        length_scales=length_scales or (0.75, 1.0, 1.25),
        file_names=file_names,
    )

    for path in Path(output_dir).glob("*.wav"):
        if sf.info(path).samplerate != 16000:
            audio, _ = librosa.load(path, sr=16000, mono=True)
            sf.write(path, audio, 16000, subtype="PCM_16")

def main():
    pass
'''

# 2. Deploy adapter across all relevant module lookup paths
target_paths = [
    Path("/content/piper-sample-generator/generate_samples.py"),
    Path("/content/piper-sample-generator/piper_sample_generator/generate_samples.py"),
    Path("/content/openWakeWord/openwakeword/generate_samples.py")
]

for p in target_paths:
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(adapter_code, encoding="utf-8")

# 3. Patch torchaudio soundfile backend in torch_audiomentations and sph_harm in acoustics
!/content/.venv/bin/python -c "import importlib.util, os; spec = importlib.util.find_spec('torch_audiomentations'); io_file = os.path.join(spec.submodule_search_locations[0], 'utils', 'io.py'); content = open(io_file, 'r').read(); open(io_file, 'w').write(content.replace('torchaudio.set_audio_backend(\"soundfile\")', '# torchaudio.set_audio_backend(\"soundfile\")'))"
!/content/.venv/bin/python -c "import importlib.util, os; spec = importlib.util.find_spec('acoustics'); directivity = os.path.join(spec.submodule_search_locations[0], 'directivity.py'); content = open(directivity, 'r').read(); open(directivity, 'w').write(content.replace('from scipy.special import sph_harm', 'try:\n    from scipy.special import sph_harm\nexcept ImportError:\n    sph_harm = None'))"

# 4. Environment patches: silence Numba debug spam and bridge torchaudio.load/info to soundfile
sitecustomize_code = '''import logging
logging.getLogger('numba').setLevel(logging.WARNING)

try:
    import soundfile as sf
    import torch
    import torchaudio

    def _sf_load(uri, frame_offset=0, num_frames=-1, channels_first=True, **kwargs):
        frames = num_frames if num_frames is not None and num_frames > 0 else -1
        data, sr = sf.read(uri, dtype='float32', start=frame_offset, frames=frames)
        t = torch.from_numpy(data.T if data.ndim > 1 else data.reshape(1, -1))
        return (t if channels_first else t.T), sr

    class _MetaData:
        def __init__(self, sr, frames, channels):
            self.sample_rate = sr
            self.num_frames = frames
            self.num_channels = channels

    def _sf_info(uri, **kwargs):
        i = sf.info(uri)
        return _MetaData(i.samplerate, i.frames, i.channels)

    torchaudio.load = _sf_load
    torchaudio.info = _sf_info
except Exception:
    pass
'''

for sp in Path("/content/.venv/lib").glob("python*/site-packages"):
    (sp / "sitecustomize.py").write_text(sitecustomize_code)

print("All compatibility adapters and patches deployed.")

# Commented out IPython magic to ensure Python compatibility.
# %cd /content

!mkdir -p /content/openWakeWord/openwakeword/resources/models /content/piper-sample-generator/models /content/output /content/configs

# Base ONNX and TFLite embedding models
!wget -nc -q https://github.com/dscripka/openWakeWord/releases/download/v0.5.1/embedding_model.onnx -P /content/openWakeWord/openwakeword/resources/models/
!wget -nc -q https://github.com/dscripka/openWakeWord/releases/download/v0.5.1/embedding_model.tflite -P /content/openWakeWord/openwakeword/resources/models/
!wget -nc -q https://github.com/dscripka/openWakeWord/releases/download/v0.5.1/melspectrogram.onnx -P /content/openWakeWord/openwakeword/resources/models/
!wget -nc -q https://github.com/dscripka/openWakeWord/releases/download/v0.5.1/melspectrogram.tflite -P /content/openWakeWord/openwakeword/resources/models/

# Piper TTS voice model
!wget -nc -q https://github.com/rhasspy/piper-sample-generator/releases/download/v2.0.0/en_US-libritts_r-medium.pt -O /content/piper-sample-generator/models/en_US-libritts_r-medium.pt

# Pre-computed negative feature datasets
!wget -nc -q --show-progress https://huggingface.co/datasets/davidscripka/openwakeword_features/resolve/main/openwakeword_features_ACAV100M_2000_hrs_16bit.npy -O /content/openwakeword_features_ACAV100M_2000_hrs_16bit.npy
!wget -nc -q --show-progress https://huggingface.co/datasets/davidscripka/openwakeword_features/resolve/main/validation_set_features.npy -O /content/validation_set_features.npy

import yaml

config = {
    'target_phrase': ['Orion', 'Oh Ryan'],
    'model_name': 'orion_model',
    'model_type': 'dnn',
    'output_dir': '/content/output',
    'piper_sample_generator_path': '/content/piper-sample-generator',
    'n_samples': 1000,
    'n_samples_val': 200,
    'tts_batch_size': 50,
    'augmentation_batch_size': 16,
    'augmentation_rounds': 1,
    'background_paths': [],
    'background_paths_duplication_rate': [],
    'custom_negative_phrases': [],
    'rir_paths': [],
    'deverb_clips': False,
    'augmentation_options': {'impulse_response': False, 'background_noise': False},
    'batch_n_per_class': {'ACAV100M_sample': 1024, 'adversarial_negative': 50, 'positive': 50},
    'layer_size': 32,
    'max_negative_weight': 1500,
    'steps': 10000,
    'target_accuracy': 0.7,
    'target_false_positives_per_hour': 0.2,
    'target_recall': 0.5,
    'false_positive_validation_data_path': '/content/validation_set_features.npy',
    'feature_data_files': {'ACAV100M_sample': '/content/openwakeword_features_ACAV100M_2000_hrs_16bit.npy'},
    'piper_sample_generator': {'piper_path': 'piper', 'use_cuda': True},
    'feature_config': {'sample_rate': 16000, 'clip_duration': 1.5}
}

with open("/content/configs/orion.yaml", "w", encoding="utf-8") as f:
    yaml.dump(config, f, default_flow_style=False)

print("Configuration /content/configs/orion.yaml generated successfully.")

# Commented out IPython magic to ensure Python compatibility.
# %cd /content

# Clear existing intermediate features and corrupted phonemizer checkpoints
!rm -f /content/output/orion_model/*.npy /content/openWakeWord/openwakeword/resources/en_us_cmudict_forward.pt

# Run openWakeWord training
!PYTHONPATH="/content/openWakeWord:/content/piper-sample-generator:$PYTHONPATH" \
 MPLBACKEND=agg \
 /content/.venv/bin/python /content/openWakeWord/openwakeword/train.py \
 --training_config /content/configs/orion.yaml \
 --generate_clips \
 --augment_clips \
 --train_model \
 --convert_to_tflite

# Convert ONNX to final TFLite runtime
!/content/.venv/bin/onnx2tf -i /content/output/orion_model.onnx -o /content/output/tflite_output